export * from './Hamburger';
export * from './Close';
export * from './LogoFull';
export * from './ArrowBig';
export * from './ArrowLeftCircle';
export * from './ArrowRightCircle';
export * from './LogoBig';
export * from './FooterLogo';
export * from './Unmute';
export * from './NameEn';
export * from './EmailEn';
export * from './MessageEn';
export * from './ContactEn';
export * from './EmailMobileEn';
export * from './MessageMobileEn';
export * from './NameMobileEn';
export * from './Mute';
export * from './Error';
export * from './Thanks';
export * from './ErrorMessage';
export * from './ScrollDown';
export * from './SupercarHeading';
export * from './OvMediaLogo';
export * from './SocClient';
export * from './Buggati';
export * from './Rimac';
export * from './Pagani';
export * from './TimelinePoint';
export * from './SocViews';
export * from './PlayButton';
export * from './Quote';
export * from './SwipeRight';
export * from './SocViewMobile';

export type IconProps = {
  width?: string;
  height?: string;
  color?: string;
};
